GET {{host}}/getmessage?name=AzureFunctions

###
GET {{{host}}}/getmessage
Content-Type: application/json

{
    "name": "Functions on Azure"
}

###
GET {{host}}/api/getmessage

###
GET {{host}}/getmessage
Content-Type: application/json

{
    "name": ""
}