[project]
name = "subspace"
version = "0.1.0"
description = "A Python project for subspace communication"
authors = [{ name = "Ryan Hill" }]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
